// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuAhmlNQWSfFbVdLYxpOP3iT3KT3RFfXc',
    appId: '1:180668270503:web:9112a68005a0e6b32f1882',
    messagingSenderId: '180668270503',
    projectId: 'vc-space-dev',
    authDomain: 'vc-space-dev.firebaseapp.com',
    storageBucket: 'vc-space-dev.appspot.com',
    measurementId: 'G-KEFW9TXS2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHOocjyKCqI-1mGu_IFknz7yQ8BKiTnhc',
    appId: '1:180668270503:android:aa7e4f25188772ea2f1882',
    messagingSenderId: '180668270503',
    projectId: 'vc-space-dev',
    storageBucket: 'vc-space-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChuRj8oe5-3jENyO4YGtk_eUdVkRYIg2w',
    appId: '1:180668270503:ios:2b2c34a82e5548602f1882',
    messagingSenderId: '180668270503',
    projectId: 'vc-space-dev',
    storageBucket: 'vc-space-dev.appspot.com',
    iosClientId: '180668270503-mmv3djum5orcsnr3dqbcni6ips1nt5m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.vcSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChuRj8oe5-3jENyO4YGtk_eUdVkRYIg2w',
    appId: '1:180668270503:ios:2b2c34a82e5548602f1882',
    messagingSenderId: '180668270503',
    projectId: 'vc-space-dev',
    storageBucket: 'vc-space-dev.appspot.com',
    iosClientId: '180668270503-mmv3djum5orcsnr3dqbcni6ips1nt5m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.vcSpace',
  );
}
